package botanyModels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelVibrantBloom extends ModelBase
{
  //fields
    ModelRenderer stem;
    ModelRenderer stemTop;
    ModelRenderer center;
    ModelRenderer heart;
    ModelRenderer stemRightFront;
    ModelRenderer stemRightFrontOne;
    ModelRenderer stemLeftFront;
    ModelRenderer stemRightBack;
    ModelRenderer root;
    ModelRenderer petalTopRight;
    ModelRenderer petalTopRightBack;
    ModelRenderer petalTopLeftBack;
    ModelRenderer petalTopLeft;
    ModelRenderer petalMiddleLeft;
    ModelRenderer petalMiddleRight;
    ModelRenderer petalMiddleLeftBack;
    ModelRenderer petalMiddleRightBack;
    ModelRenderer petalBottomLeft;
    ModelRenderer petalBottomLeftBack;
    ModelRenderer petalBottomRight;
    ModelRenderer petalBottomRightBack;
    ModelRenderer petalTipLeft;
    ModelRenderer petalTipLeftBack;
    ModelRenderer petalTipRightBack;
    ModelRenderer petalTipLeftBackOne;
    ModelRenderer lipOne;
    ModelRenderer lipTwo;
    ModelRenderer lipThree;
    ModelRenderer lipFour;
    ModelRenderer lipFive;
    ModelRenderer lipSix;
    ModelRenderer lipSeven;
    ModelRenderer lipEight;
    ModelRenderer cornerOne;
    ModelRenderer cornerTwo;
    ModelRenderer cornerThree;
    ModelRenderer cornerFour;
    ModelRenderer pollenStemOne;
    ModelRenderer pollenStemTwo;
    ModelRenderer pollenStemThree;
    ModelRenderer pollenStemFour;
    ModelRenderer pollenStemFive;
    ModelRenderer pollenStemSix;
    ModelRenderer pollenStemSeven;
    ModelRenderer pollenStemEight;
  
  public ModelVibrantBloom()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      stem = new ModelRenderer(this, 0, 0);
      stem.addBox(-4F, -1F, -4F, 8, 4, 8);
      stem.setRotationPoint(0F, 20F, 0F);
      stem.setTextureSize(64, 128);
      stem.mirror = true;
      setRotation(stem, 0F, 0F, 0F);
      stemTop = new ModelRenderer(this, 0, 20);
      stemTop.addBox(-6F, -2F, -6F, 12, 4, 12);
      stemTop.setRotationPoint(0F, 17.5F, 0F);
      stemTop.setTextureSize(64, 128);
      stemTop.mirror = true;
      setRotation(stemTop, 0F, 0F, 0F);
      center = new ModelRenderer(this, 0, 37);
      center.addBox(-5F, 0F, -5F, 10, 2, 10);
      center.setRotationPoint(0F, 14F, 0F);
      center.setTextureSize(64, 128);
      center.mirror = true;
      setRotation(center, 0F, -0.7853982F, 0F);
      heart = new ModelRenderer(this, 0, 50);
      heart.addBox(-3F, 0F, -3F, 6, 3, 6);
      heart.setRotationPoint(0F, 11F, 0F);
      heart.setTextureSize(64, 128);
      heart.mirror = true;
      setRotation(heart, 0F, 0F, 0F);
      stemRightFront = new ModelRenderer(this, 0, 60);
      stemRightFront.addBox(0F, 0F, -2F, 7, 2, 4);
      stemRightFront.setRotationPoint(4F, 19F, 4F);
      stemRightFront.setTextureSize(64, 128);
      stemRightFront.mirror = true;
      setRotation(stemRightFront, 0F, -0.7853982F, 0F);
      stemRightFrontOne = new ModelRenderer(this, 0, 60);
      stemRightFrontOne.addBox(-7F, 3F, -2F, 7, 2, 4);
      stemRightFrontOne.setRotationPoint(-4F, 16F, -4F);
      stemRightFrontOne.setTextureSize(64, 128);
      stemRightFrontOne.mirror = true;
      setRotation(stemRightFrontOne, 0F, -0.7853982F, 0F);
      stemLeftFront = new ModelRenderer(this, 0, 60);
      stemLeftFront.addBox(0F, 0F, -2F, 7, 2, 4);
      stemLeftFront.setRotationPoint(4F, 19F, -4F);
      stemLeftFront.setTextureSize(64, 128);
      stemLeftFront.mirror = true;
      setRotation(stemLeftFront, 0F, 0.7853982F, 0F);
      stemRightBack = new ModelRenderer(this, 0, 60);
      stemRightBack.addBox(-7F, 0F, -2F, 7, 2, 4);
      stemRightBack.setRotationPoint(-4F, 19F, 4F);
      stemRightBack.setTextureSize(64, 128);
      stemRightBack.mirror = true;
      setRotation(stemRightBack, 0F, 0.7853982F, 0F);
      root = new ModelRenderer(this, 0, 13);
      root.addBox(-3F, 0F, -3F, 6, 1, 6);
      root.setRotationPoint(0F, 23F, 0F);
      root.setTextureSize(64, 128);
      root.mirror = true;
      setRotation(root, 0F, 0F, 0F);
      petalTopRight = new ModelRenderer(this, 0, 68);
      petalTopRight.addBox(-8F, 0F, -3F, 8, 2, 6);
      petalTopRight.setRotationPoint(-5F, 15F, -5F);
      petalTopRight.setTextureSize(64, 128);
      petalTopRight.mirror = true;
      setRotation(petalTopRight, 0F, -0.7853982F, 0F);
      petalTopRightBack = new ModelRenderer(this, 0, 68);
      petalTopRightBack.addBox(-8F, 0F, -3F, 8, 2, 6);
      petalTopRightBack.setRotationPoint(-5F, 15F, 5F);
      petalTopRightBack.setTextureSize(64, 128);
      petalTopRightBack.mirror = true;
      setRotation(petalTopRightBack, 0F, 0.7853982F, 0F);
      petalTopLeftBack = new ModelRenderer(this, 0, 68);
      petalTopLeftBack.addBox(0F, 0F, -3F, 8, 2, 6);
      petalTopLeftBack.setRotationPoint(5F, 15F, 5F);
      petalTopLeftBack.setTextureSize(64, 128);
      petalTopLeftBack.mirror = true;
      setRotation(petalTopLeftBack, 0F, -0.7853982F, 0F);
      petalTopLeft = new ModelRenderer(this, 0, 68);
      petalTopLeft.addBox(0F, 0F, -3F, 8, 2, 6);
      petalTopLeft.setRotationPoint(5F, 15F, -5F);
      petalTopLeft.setTextureSize(64, 128);
      petalTopLeft.mirror = true;
      setRotation(petalTopLeft, 0F, 0.7853982F, 0F);
      petalMiddleLeft = new ModelRenderer(this, 0, 78);
      petalMiddleLeft.addBox(-6F, 0F, -14F, 12, 3, 14);
      petalMiddleLeft.setRotationPoint(-4F, 16F, -4F);
      petalMiddleLeft.setTextureSize(64, 128);
      petalMiddleLeft.mirror = true;
      setRotation(petalMiddleLeft, 0F, 0.7853982F, 0F);
      petalMiddleRight = new ModelRenderer(this, 0, 78);
      petalMiddleRight.addBox(-6F, 0F, -14F, 12, 3, 14);
      petalMiddleRight.setRotationPoint(4F, 16F, -4F);
      petalMiddleRight.setTextureSize(64, 128);
      petalMiddleRight.mirror = true;
      setRotation(petalMiddleRight, 0F, -0.7853982F, 0F);
      petalMiddleLeftBack = new ModelRenderer(this, 0, 78);
      petalMiddleLeftBack.addBox(-6F, 0F, 0F, 12, 3, 14);
      petalMiddleLeftBack.setRotationPoint(4F, 16F, 4F);
      petalMiddleLeftBack.setTextureSize(64, 128);
      petalMiddleLeftBack.mirror = true;
      setRotation(petalMiddleLeftBack, 0F, 0.7853982F, 0F);
      petalMiddleRightBack = new ModelRenderer(this, 0, 78);
      petalMiddleRightBack.addBox(-6F, 0F, 0F, 12, 3, 14);
      petalMiddleRightBack.setRotationPoint(-4F, 16F, 4F);
      petalMiddleRightBack.setTextureSize(64, 128);
      petalMiddleRightBack.mirror = true;
      setRotation(petalMiddleRightBack, 0F, -0.7853982F, 0F);
      petalBottomLeft = new ModelRenderer(this, 0, 96);
      petalBottomLeft.addBox(-4F, 0F, -8F, 8, 2, 8);
      petalBottomLeft.setRotationPoint(14F, 16F, -14F);
      petalBottomLeft.setTextureSize(64, 128);
      petalBottomLeft.mirror = true;
      setRotation(petalBottomLeft, 0.1745329F, -0.7853982F, 0F);
      petalBottomLeftBack = new ModelRenderer(this, 0, 96);
      petalBottomLeftBack.addBox(-4F, 0F, -8F, 8, 2, 8);
      petalBottomLeftBack.setRotationPoint(14F, 16F, 14F);
      petalBottomLeftBack.setTextureSize(64, 128);
      petalBottomLeftBack.mirror = true;
      setRotation(petalBottomLeftBack, 0.1745329F, -2.356194F, 0F);
      petalBottomRight = new ModelRenderer(this, 0, 96);
      petalBottomRight.addBox(-4F, 0F, -8F, 8, 2, 8);
      petalBottomRight.setRotationPoint(-14F, 16F, -14F);
      petalBottomRight.setTextureSize(64, 128);
      petalBottomRight.mirror = true;
      setRotation(petalBottomRight, 0.1745329F, 0.7853982F, 0F);
      petalBottomRightBack = new ModelRenderer(this, 0, 96);
      petalBottomRightBack.addBox(-4F, 0F, -8F, 8, 2, 8);
      petalBottomRightBack.setRotationPoint(-14F, 16F, 14F);
      petalBottomRightBack.setTextureSize(64, 128);
      petalBottomRightBack.mirror = true;
      setRotation(petalBottomRightBack, 0.1745329F, 2.356194F, 0F);
      petalTipLeft = new ModelRenderer(this, 0, 108);
      petalTipLeft.addBox(-2F, 0F, -6F, 4, 1, 6);
      petalTipLeft.setRotationPoint(19F, 18F, -19F);
      petalTipLeft.setTextureSize(64, 128);
      petalTipLeft.mirror = true;
      setRotation(petalTipLeft, 0.3490659F, -0.7853982F, 0F);
      petalTipLeftBack = new ModelRenderer(this, 0, 108);
      petalTipLeftBack.addBox(-2F, 0F, 0F, 4, 1, 6);
      petalTipLeftBack.setRotationPoint(19F, 18F, 19F);
      petalTipLeftBack.setTextureSize(64, 128);
      petalTipLeftBack.mirror = true;
      setRotation(petalTipLeftBack, -0.3490659F, 0.7853982F, 0F);
      petalTipRightBack = new ModelRenderer(this, 0, 108);
      petalTipRightBack.addBox(-2F, 0F, 0F, 4, 1, 6);
      petalTipRightBack.setRotationPoint(-19F, 18F, 19F);
      petalTipRightBack.setTextureSize(64, 128);
      petalTipRightBack.mirror = true;
      setRotation(petalTipRightBack, -0.3490659F, -0.7853982F, 0F);
      petalTipLeftBackOne = new ModelRenderer(this, 0, 108);
      petalTipLeftBackOne.addBox(-2F, 0F, -6F, 4, 1, 6);
      petalTipLeftBackOne.setRotationPoint(-19F, 18F, -19F);
      petalTipLeftBackOne.setTextureSize(64, 128);
      petalTipLeftBackOne.mirror = true;
      setRotation(petalTipLeftBackOne, 0.3490659F, 0.7853982F, 0F);
      lipOne = new ModelRenderer(this, 0, 117);
      lipOne.addBox(-4F, 0F, -6F, 4, 2, 8);
      lipOne.setRotationPoint(-12F, 16F, -4F);
      lipOne.setTextureSize(64, 128);
      lipOne.mirror = true;
      setRotation(lipOne, 0F, 0.7853982F, 0.2617994F);
      lipTwo = new ModelRenderer(this, 0, 117);
      lipTwo.addBox(-4F, 0F, -2F, 4, 2, 8);
      lipTwo.setRotationPoint(-12F, 16F, 4F);
      lipTwo.setTextureSize(64, 128);
      lipTwo.mirror = true;
      setRotation(lipTwo, 0F, -0.7853982F, 0.2617994F);
      lipThree = new ModelRenderer(this, 0, 117);
      lipThree.addBox(-4F, 0F, -6F, 4, 2, 8);
      lipThree.setRotationPoint(-4F, 16F, 12F);
      lipThree.setTextureSize(64, 128);
      lipThree.mirror = true;
      setRotation(lipThree, 0F, 2.356194F, 0.2617994F);
      lipFour = new ModelRenderer(this, 0, 117);
      lipFour.addBox(-4F, 0F, -2F, 4, 2, 8);
      lipFour.setRotationPoint(4F, 16F, 12F);
      lipFour.setTextureSize(64, 128);
      lipFour.mirror = true;
      setRotation(lipFour, 0F, 0.7853982F, 0.2617994F);
      lipFive = new ModelRenderer(this, 0, 117);
      lipFive.addBox(-4F, 0F, -6F, 4, 2, 8);
      lipFive.setRotationPoint(12F, 16F, 4F);
      lipFive.setTextureSize(64, 128);
      lipFive.mirror = true;
      setRotation(lipFive, 0F, -2.356194F, 0.2617994F);
      lipSix = new ModelRenderer(this, 0, 117);
      lipSix.addBox(-4F, 0F, -2F, 4, 2, 8);
      lipSix.setRotationPoint(12F, 16F, -4F);
      lipSix.setTextureSize(64, 128);
      lipSix.mirror = true;
      setRotation(lipSix, 0F, 2.356194F, 0.2617994F);
      lipSeven = new ModelRenderer(this, 0, 117);
      lipSeven.addBox(-4F, 0F, -6F, 4, 2, 8);
      lipSeven.setRotationPoint(4F, 16F, -12F);
      lipSeven.setTextureSize(64, 128);
      lipSeven.mirror = true;
      setRotation(lipSeven, 0F, -0.7853982F, 0.2617994F);
      lipEight = new ModelRenderer(this, 0, 117);
      lipEight.addBox(-4F, 0F, -2F, 4, 2, 8);
      lipEight.setRotationPoint(-4F, 16F, -12F);
      lipEight.setTextureSize(64, 128);
      lipEight.mirror = true;
      setRotation(lipEight, 0F, -2.356194F, 0.2617994F);
      cornerOne = new ModelRenderer(this, 34, 0);
      cornerOne.addBox(0F, 0F, 0F, 4, 1, 4);
      cornerOne.setRotationPoint(8F, 17F, 0F);
      cornerOne.setTextureSize(64, 128);
      cornerOne.mirror = true;
      setRotation(cornerOne, 0.2617994F, 0.7853982F, -0.2617994F);
      cornerTwo = new ModelRenderer(this, 34, 0);
      cornerTwo.addBox(0F, 0F, 0F, 4, 1, 4);
      cornerTwo.setRotationPoint(0F, 17F, 8F);
      cornerTwo.setTextureSize(64, 128);
      cornerTwo.mirror = true;
      setRotation(cornerTwo, 0.2617994F, -0.7853982F, -0.2617994F);
      cornerThree = new ModelRenderer(this, 34, 0);
      cornerThree.addBox(0F, 0F, 0F, 4, 1, 4);
      cornerThree.setRotationPoint(0F, 17F, -8F);
      cornerThree.setTextureSize(64, 128);
      cornerThree.mirror = true;
      setRotation(cornerThree, 0.2617994F, 2.356194F, -0.2617994F);
      cornerFour = new ModelRenderer(this, 34, 0);
      cornerFour.addBox(0F, 0F, 0F, 4, 1, 4);
      cornerFour.setRotationPoint(-8F, 17F, 0F);
      cornerFour.setTextureSize(64, 128);
      cornerFour.mirror = true;
      setRotation(cornerFour, 0.2617994F, -2.356194F, -0.2617994F);
      pollenStemOne = new ModelRenderer(this, 38, 8);
      pollenStemOne.addBox(-1F, -6F, -1F, 2, 6, 2);
      pollenStemOne.setRotationPoint(4F, 15F, 0F);
      pollenStemOne.setTextureSize(64, 128);
      pollenStemOne.mirror = true;
      setRotation(pollenStemOne, 0F, 0F, 0.5235988F);
      pollenStemTwo = new ModelRenderer(this, 38, 8);
      pollenStemTwo.addBox(-1F, -6F, -1F, 2, 6, 2);
      pollenStemTwo.setRotationPoint(-4F, 15F, 0F);
      pollenStemTwo.setTextureSize(64, 128);
      pollenStemTwo.mirror = true;
      setRotation(pollenStemTwo, 0F, 0F, -0.5235988F);
      pollenStemThree = new ModelRenderer(this, 38, 8);
      pollenStemThree.addBox(-1F, -6F, -1F, 2, 6, 2);
      pollenStemThree.setRotationPoint(0F, 15F, -4F);
      pollenStemThree.setTextureSize(64, 128);
      pollenStemThree.mirror = true;
      setRotation(pollenStemThree, 0.5235988F, 0F, 0F);
      pollenStemFour = new ModelRenderer(this, 38, 8);
      pollenStemFour.addBox(-1F, -6F, -1F, 2, 6, 2);
      pollenStemFour.setRotationPoint(0F, 15F, 4F);
      pollenStemFour.setTextureSize(64, 128);
      pollenStemFour.mirror = true;
      setRotation(pollenStemFour, -0.5235988F, 0F, 0F);
      pollenStemFive = new ModelRenderer(this, 38, 52);
      pollenStemFive.addBox(-1F, -6F, -1F, 1, 6, 1);
      pollenStemFive.setRotationPoint(0F, 10F, -6F);
      pollenStemFive.setTextureSize(64, 128);
      pollenStemFive.mirror = true;
      setRotation(pollenStemFive, 0.7853982F, -0.6632251F, -0.7853982F);
      pollenStemSix = new ModelRenderer(this, 38, 52);
      pollenStemSix.addBox(0F, -6F, 0F, 1, 6, 1);
      pollenStemSix.setRotationPoint(0F, 10F, 6F);
      pollenStemSix.setTextureSize(64, 128);
      pollenStemSix.mirror = true;
      setRotation(pollenStemSix, -0.7853982F, -0.6457718F, 0.7853982F);
      pollenStemSeven = new ModelRenderer(this, 38, 52);
      pollenStemSeven.addBox(-1F, -6F, 0F, 1, 6, 1);
      pollenStemSeven.setRotationPoint(-6F, 10F, 0F);
      pollenStemSeven.setTextureSize(64, 128);
      pollenStemSeven.mirror = true;
      setRotation(pollenStemSeven, -0.7853982F, -0.9599311F, -0.7853982F);
      pollenStemEight = new ModelRenderer(this, 38, 52);
      pollenStemEight.addBox(0F, -6F, 0F, 1, 6, 1);
      pollenStemEight.setRotationPoint(6F, 10F, 0F);
      pollenStemEight.setTextureSize(64, 128);
      pollenStemEight.mirror = true;
      setRotation(pollenStemEight, -0.7853982F, 0.7853982F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    stem.render(f5);
    stemTop.render(f5);
    center.render(f5);
    heart.render(f5);
    stemRightFront.render(f5);
    stemRightFrontOne.render(f5);
    stemLeftFront.render(f5);
    stemRightBack.render(f5);
    root.render(f5);
    petalTopRight.render(f5);
    petalTopRightBack.render(f5);
    petalTopLeftBack.render(f5);
    petalTopLeft.render(f5);
    petalMiddleLeft.render(f5);
    petalMiddleRight.render(f5);
    petalMiddleLeftBack.render(f5);
    petalMiddleRightBack.render(f5);
    petalBottomLeft.render(f5);
    petalBottomLeftBack.render(f5);
    petalBottomRight.render(f5);
    petalBottomRightBack.render(f5);
    petalTipLeft.render(f5);
    petalTipLeftBack.render(f5);
    petalTipRightBack.render(f5);
    petalTipLeftBackOne.render(f5);
    lipOne.render(f5);
    lipTwo.render(f5);
    lipThree.render(f5);
    lipFour.render(f5);
    lipFive.render(f5);
    lipSix.render(f5);
    lipSeven.render(f5);
    lipEight.render(f5);
    cornerOne.render(f5);
    cornerTwo.render(f5);
    cornerThree.render(f5);
    cornerFour.render(f5);
    pollenStemOne.render(f5);
    pollenStemTwo.render(f5);
    pollenStemThree.render(f5);
    pollenStemFour.render(f5);
    pollenStemFive.render(f5);
    pollenStemSix.render(f5);
    pollenStemSeven.render(f5);
    pollenStemEight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public void renderModel(float f)
  {
	    stem.render(f);
	    stemTop.render(f);
	    center.render(f);
	    heart.render(f);
	    stemRightFront.render(f);
	    stemRightFrontOne.render(f);
	    stemLeftFront.render(f);
	    stemRightBack.render(f);
	    root.render(f);
	    petalTopRight.render(f);
	    petalTopRightBack.render(f);
	    petalTopLeftBack.render(f);
	    petalTopLeft.render(f);
	    petalMiddleLeft.render(f);
	    petalMiddleRight.render(f);
	    petalMiddleLeftBack.render(f);
	    petalMiddleRightBack.render(f);
	    petalBottomLeft.render(f);
	    petalBottomLeftBack.render(f);
	    petalBottomRight.render(f);
	    petalBottomRightBack.render(f);
	    petalTipLeft.render(f);
	    petalTipLeftBack.render(f);
	    petalTipRightBack.render(f);
	    petalTipLeftBackOne.render(f);
	    lipOne.render(f);
	    lipTwo.render(f);
	    lipThree.render(f);
	    lipFour.render(f);
	    lipFive.render(f);
	    lipSix.render(f);
	    lipSeven.render(f);
	    lipEight.render(f);
	    cornerOne.render(f);
	    cornerTwo.render(f);
	    cornerThree.render(f);
	    cornerFour.render(f);
	    pollenStemOne.render(f);
	    pollenStemTwo.render(f);
	    pollenStemThree.render(f);
	    pollenStemFour.render(f);
	    pollenStemFive.render(f);
	    pollenStemSix.render(f);
	    pollenStemSeven.render(f);
	    pollenStemEight.render(f);
  }
}
