package botanyModels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPowerStaff extends ModelBase
{
  //fields
    ModelRenderer staffHandle;
    ModelRenderer staffPlatform0;
    ModelRenderer staffPlatformShort1;
    ModelRenderer staffPlatformShort2;
    ModelRenderer staffPlatformLong1;
    ModelRenderer staffPlatformLong2;
    ModelRenderer vine0;
    ModelRenderer vine1;
    ModelRenderer vine2;
    ModelRenderer vine3;
    ModelRenderer vine4;
    ModelRenderer vine5;
    ModelRenderer vine6;
    ModelRenderer vine7;
    ModelRenderer vine8;
    ModelRenderer vine9;
    ModelRenderer vine10;
    ModelRenderer vine11;
    ModelRenderer vine12;
    ModelRenderer vine13;
    ModelRenderer vine14;
    ModelRenderer vine15;
    ModelRenderer vine16;
    ModelRenderer thorn1;
    ModelRenderer thorn2;
    ModelRenderer thorn3;
    ModelRenderer thorn4;
    ModelRenderer thorn5;
    ModelRenderer thorn6;
    ModelRenderer thorn7;
    ModelRenderer thorn8;
  
  public ModelPowerStaff()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      staffHandle = new ModelRenderer(this, 0, 0);
      staffHandle.addBox(-1F, -1F, -1F, 2, 24, 2);
      staffHandle.setRotationPoint(0F, 1F, 0F);
      staffHandle.setTextureSize(64, 32);
      staffHandle.mirror = true;
      setRotation(staffHandle, 0F, 0F, 0F);
      staffPlatform0 = new ModelRenderer(this, 9, 0);
      staffPlatform0.addBox(-1F, -1F, -1F, 6, 1, 6);
      staffPlatform0.setRotationPoint(-2F, 0F, -2F);
      staffPlatform0.setTextureSize(64, 32);
      staffPlatform0.mirror = true;
      setRotation(staffPlatform0, 0F, 0F, 0F);
      staffPlatformShort1 = new ModelRenderer(this, 9, 8);
      staffPlatformShort1.addBox(0F, 0F, 0F, 1, 1, 4);
      staffPlatformShort1.setRotationPoint(2F, -2F, -2F);
      staffPlatformShort1.setTextureSize(64, 32);
      staffPlatformShort1.mirror = true;
      setRotation(staffPlatformShort1, 0F, 0F, 0F);
      staffPlatformShort2 = new ModelRenderer(this, 19, 8);
      staffPlatformShort2.addBox(0F, 0F, 0F, 1, 1, 4);
      staffPlatformShort2.setRotationPoint(-3F, -2F, -2F);
      staffPlatformShort2.setTextureSize(64, 32);
      staffPlatformShort2.mirror = true;
      setRotation(staffPlatformShort2, 0F, 0F, 0F);
      staffPlatformLong1 = new ModelRenderer(this, 9, 14);
      staffPlatformLong1.addBox(0F, 0F, 0F, 6, 1, 1);
      staffPlatformLong1.setRotationPoint(-3F, -2F, -3F);
      staffPlatformLong1.setTextureSize(64, 32);
      staffPlatformLong1.mirror = true;
      setRotation(staffPlatformLong1, 0F, 0F, 0F);
      staffPlatformLong2 = new ModelRenderer(this, 9, 16);
      staffPlatformLong2.addBox(0F, 0F, 0F, 6, 1, 1);
      staffPlatformLong2.setRotationPoint(-3F, -2F, 2F);
      staffPlatformLong2.setTextureSize(64, 32);
      staffPlatformLong2.mirror = true;
      setRotation(staffPlatformLong2, 0F, 0F, 0F);
      vine0 = new ModelRenderer(this, 54, 0);
      vine0.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine0.setRotationPoint(1.5F, 23.5F, -0.5F);
      vine0.setTextureSize(64, 32);
      vine0.mirror = true;
      setRotation(vine0, 0F, 0F, 0F);
      vine1 = new ModelRenderer(this, 60, 24);
      vine1.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine1.setRotationPoint(1.5F, 21.5F, 0.5F);
      vine1.setTextureSize(64, 32);
      vine1.mirror = true;
      setRotation(vine1, 0F, 0F, 0F);
      vine2 = new ModelRenderer(this, 54, 2);
      vine2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine2.setRotationPoint(0.5F, 20.5F, 1.5F);
      vine2.setTextureSize(64, 32);
      vine2.mirror = true;
      setRotation(vine2, 0F, 0F, 0F);
      vine3 = new ModelRenderer(this, 60, 21);
      vine3.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine3.setRotationPoint(-0.5F, 18.5F, 1.5F);
      vine3.setTextureSize(64, 32);
      vine3.mirror = true;
      setRotation(vine3, 0F, 0F, 0F);
      vine4 = new ModelRenderer(this, 54, 4);
      vine4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine4.setRotationPoint(-1.5F, 17.5F, 0.5F);
      vine4.setTextureSize(64, 32);
      vine4.mirror = true;
      setRotation(vine4, 0F, 0F, 0F);
      vine5 = new ModelRenderer(this, 60, 18);
      vine5.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine5.setRotationPoint(-1.5F, 15.5F, -0.5F);
      vine5.setTextureSize(64, 32);
      vine5.mirror = true;
      setRotation(vine5, 0F, 0F, 0F);
      vine6 = new ModelRenderer(this, 54, 6);
      vine6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine6.setRotationPoint(-0.5F, 14.5F, -1.5F);
      vine6.setTextureSize(64, 32);
      vine6.mirror = true;
      setRotation(vine6, 0F, 0F, 0F);
      vine7 = new ModelRenderer(this, 60, 15);
      vine7.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine7.setRotationPoint(0.5F, 12.5F, -1.5F);
      vine7.setTextureSize(64, 32);
      vine7.mirror = true;
      setRotation(vine7, 0F, 0F, 0F);
      vine8 = new ModelRenderer(this, 54, 8);
      vine8.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine8.setRotationPoint(1.5F, 11.5F, -0.5F);
      vine8.setTextureSize(64, 32);
      vine8.mirror = true;
      setRotation(vine8, 0F, 0F, 0F);
      vine9 = new ModelRenderer(this, 60, 12);
      vine9.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine9.setRotationPoint(1.5F, 9.5F, 0.5F);
      vine9.setTextureSize(64, 32);
      vine9.mirror = true;
      setRotation(vine9, 0F, 0F, 0F);
      vine10 = new ModelRenderer(this, 54, 10);
      vine10.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine10.setRotationPoint(0.5F, 8.5F, 1.5F);
      vine10.setTextureSize(64, 32);
      vine10.mirror = true;
      setRotation(vine10, 0F, 0F, 0F);
      vine11 = new ModelRenderer(this, 60, 9);
      vine11.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine11.setRotationPoint(-0.5F, 6.5F, 1.5F);
      vine11.setTextureSize(64, 32);
      vine11.mirror = true;
      setRotation(vine11, 0F, 0F, 0F);
      vine12 = new ModelRenderer(this, 54, 12);
      vine12.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine12.setRotationPoint(-1.5F, 5.5F, 0.5F);
      vine12.setTextureSize(64, 32);
      vine12.mirror = true;
      setRotation(vine12, 0F, 0F, 0F);
      vine13 = new ModelRenderer(this, 60, 6);
      vine13.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine13.setRotationPoint(-1.5F, 3.5F, -0.5F);
      vine13.setTextureSize(64, 32);
      vine13.mirror = true;
      setRotation(vine13, 0F, 0F, 0F);
      vine14 = new ModelRenderer(this, 54, 14);
      vine14.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      vine14.setRotationPoint(-0.5F, 2.5F, -1.5F);
      vine14.setTextureSize(64, 32);
      vine14.mirror = true;
      setRotation(vine14, 0F, 0F, 0F);
      vine15 = new ModelRenderer(this, 60, 3);
      vine15.addBox(-0.5F, -0.5F, -0.5F, 1, 2, 1);
      vine15.setRotationPoint(0.5F, 0.5F, -1.5F);
      vine15.setTextureSize(64, 32);
      vine15.mirror = true;
      setRotation(vine15, 0F, 0F, 0F);
      vine16 = new ModelRenderer(this, 58, 0);
      vine16.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 2);
      vine16.setRotationPoint(1.5F, 0.5F, -1.5F);
      vine16.setTextureSize(64, 32);
      vine16.mirror = true;
      setRotation(vine16, 0F, 0F, 0F);
      thorn1 = new ModelRenderer(this, 9, 19);
      thorn1.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn1.setRotationPoint(2F, 10F, 0F);
      thorn1.setTextureSize(64, 32);
      thorn1.mirror = true;
      setRotation(thorn1, 0F, 0F, 0F);
      thorn2 = new ModelRenderer(this, 9, 19);
      thorn2.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn2.setRotationPoint(0F, 8F, 2F);
      thorn2.setTextureSize(64, 32);
      thorn2.mirror = true;
      setRotation(thorn2, 0F, 0F, 0F);
      thorn3 = new ModelRenderer(this, 9, 19);
      thorn3.addBox(-3F, 0F, 0F, 1, 1, 1);
      thorn3.setRotationPoint(0F, 5F, 0F);
      thorn3.setTextureSize(64, 32);
      thorn3.mirror = true;
      setRotation(thorn3, 0F, 0F, 0F);
      thorn4 = new ModelRenderer(this, 9, 19);
      thorn4.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn4.setRotationPoint(0F, 12F, -3F);
      thorn4.setTextureSize(64, 32);
      thorn4.mirror = true;
      setRotation(thorn4, 0F, 0F, 0F);
      thorn5 = new ModelRenderer(this, 9, 19);
      thorn5.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn5.setRotationPoint(-1F, 2F, -3F);
      thorn5.setTextureSize(64, 32);
      thorn5.mirror = true;
      setRotation(thorn5, 0F, 0F, 0F);
      thorn6 = new ModelRenderer(this, 9, 19);
      thorn6.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn6.setRotationPoint(-3F, 16F, -1F);
      thorn6.setTextureSize(64, 32);
      thorn6.mirror = true;
      setRotation(thorn6, 0F, 0F, 0F);
      thorn7 = new ModelRenderer(this, 9, 19);
      thorn7.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn7.setRotationPoint(-1F, 18F, 2F);
      thorn7.setTextureSize(64, 32);
      thorn7.mirror = true;
      setRotation(thorn7, 0F, 0F, 0F);
      thorn8 = new ModelRenderer(this, 9, 19);
      thorn8.addBox(0F, 0F, 0F, 1, 1, 1);
      thorn8.setRotationPoint(2F, 21F, 0F);
      thorn8.setTextureSize(64, 32);
      thorn8.mirror = true;
      setRotation(thorn8, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    staffHandle.render(f5);
    staffPlatform0.render(f5);
    staffPlatformShort1.render(f5);
    staffPlatformShort2.render(f5);
    staffPlatformLong1.render(f5);
    staffPlatformLong2.render(f5);
    vine0.render(f5);
    vine1.render(f5);
    vine2.render(f5);
    vine3.render(f5);
    vine4.render(f5);
    vine5.render(f5);
    vine6.render(f5);
    vine7.render(f5);
    vine8.render(f5);
    vine9.render(f5);
    vine10.render(f5);
    vine11.render(f5);
    vine12.render(f5);
    vine13.render(f5);
    vine14.render(f5);
    vine15.render(f5);
    vine16.render(f5);
    thorn1.render(f5);
    thorn2.render(f5);
    thorn3.render(f5);
    thorn4.render(f5);
    thorn5.render(f5);
    thorn6.render(f5);
    thorn7.render(f5);
    thorn8.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public void renderModel(float f)
  {
	    staffHandle.render(f);
	    staffPlatform0.render(f);
	    staffPlatformShort1.render(f);
	    staffPlatformShort2.render(f);
	    staffPlatformLong1.render(f);
	    staffPlatformLong2.render(f);
	    vine0.render(f);
	    vine1.render(f);
	    vine2.render(f);
	    vine3.render(f);
	    vine4.render(f);
	    vine5.render(f);
	    vine6.render(f);
	    vine7.render(f);
	    vine8.render(f);
	    vine9.render(f);
	    vine10.render(f);
	    vine11.render(f);
	    vine12.render(f);
	    vine13.render(f);
	    vine14.render(f);
	    vine15.render(f);
	    vine16.render(f);
	    thorn1.render(f);
	    thorn2.render(f);
	    thorn3.render(f);
	    thorn4.render(f);
	    thorn5.render(f);
	    thorn6.render(f);
	    thorn7.render(f);
	    thorn8.render(f);
  }
}